# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.__version__)
print(np.show_config())


2.4.6
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.31
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/Users/ec2-user/croot/numpy_and_nump

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:
### [your code here]

# 1. Using random and specifying the size of the array
a = np.random.random(size=(2,3,5))
a

# # 2. Using zeros & ones
# """
#     a = np.zeros((2,3,5))
#     a = np.ones((2,3,5))
# """

# #3. Using np.array() & np.reshape()
# """
#     a = np.array([])
#     a_3D = np.reshape(a, (2,3,5))
# """

array([[[0.46328475, 0.43723044, 0.34640176, 0.1842765 , 0.29498277],
        [0.49840228, 0.30465432, 0.22538433, 0.8161537 , 0.35192809],
        [0.30895097, 0.40848327, 0.85813124, 0.836447  , 0.57750169]],

       [[0.70594604, 0.30884175, 0.58730492, 0.32732925, 0.48585017],
        [0.47063244, 0.9885815 , 0.39780346, 0.23984912, 0.18318801],
        [0.82506318, 0.35231328, 0.66209665, 0.34971042, 0.42505079]]])


### 4. Print a.


In [8]:
### [your code here]
print(a)

[[[0.46328475 0.43723044 0.34640176 0.1842765  0.29498277]
  [0.49840228 0.30465432 0.22538433 0.8161537  0.35192809]
  [0.30895097 0.40848327 0.85813124 0.836447   0.57750169]]

 [[0.70594604 0.30884175 0.58730492 0.32732925 0.48585017]
  [0.47063244 0.9885815  0.39780346 0.23984912 0.18318801]
  [0.82506318 0.35231328 0.66209665 0.34971042 0.42505079]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [11]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [13]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
### [your code here]
if a.shape == b.shape:
    print("Array a and array b are of same size")
else:
    print("Array a and array b are not of same size")

Array a and array b are not of same size



### 8. Are you able to add a and b? Why or why not?


In [23]:
### [your code here]
"""a and b cannot be added because they are not of the same size"""

'a and b cannot be added because they are not of the same size'



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [26]:
### [your code here]
c = np.reshape(b, (2,3,5))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [28]:
### [your code here]
d = a + c
d
# It works now because the matrixes are of the same size and operations such as addition can now be performed.

array([[[1.46328475, 1.43723044, 1.34640176, 1.1842765 , 1.29498277],
        [1.49840228, 1.30465432, 1.22538433, 1.8161537 , 1.35192809],
        [1.30895097, 1.40848327, 1.85813124, 1.836447  , 1.57750169]],

       [[1.70594604, 1.30884175, 1.58730492, 1.32732925, 1.48585017],
        [1.47063244, 1.9885815 , 1.39780346, 1.23984912, 1.18318801],
        [1.82506318, 1.35231328, 1.66209665, 1.34971042, 1.42505079]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [30]:
### [your code here]
print(a)
print(c)

# Array a has float values between 1 and 0 because we used the random function to generate them, whereas array c has ineger ones for all values.

[[[0.46328475 0.43723044 0.34640176 0.1842765  0.29498277]
  [0.49840228 0.30465432 0.22538433 0.8161537  0.35192809]
  [0.30895097 0.40848327 0.85813124 0.836447   0.57750169]]

 [[0.70594604 0.30884175 0.58730492 0.32732925 0.48585017]
  [0.47063244 0.9885815  0.39780346 0.23984912 0.18318801]
  [0.82506318 0.35231328 0.66209665 0.34971042 0.42505079]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [40]:
### [your code here] 
e = a * c
e

array([[[0.46328475, 0.43723044, 0.34640176, 0.1842765 , 0.29498277],
        [0.49840228, 0.30465432, 0.22538433, 0.8161537 , 0.35192809],
        [0.30895097, 0.40848327, 0.85813124, 0.836447  , 0.57750169]],

       [[0.70594604, 0.30884175, 0.58730492, 0.32732925, 0.48585017],
        [0.47063244, 0.9885815 , 0.39780346, 0.23984912, 0.18318801],
        [0.82506318, 0.35231328, 0.66209665, 0.34971042, 0.42505079]]])



### 13. Does e equal to a? Why or why not?


In [36]:
### [your code here]
#checking if e is equal to a 
e==a

#e is equal to a, because we multipled a by 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [37]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"Max: {d_max}, min: {d_min}, mean: {d_mean}")

Max: 1.988581498243125, min: 1.1831880084043378, mean: 1.474059137049991



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [38]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [41]:
### [your code here]
for i, value in zip(np.ndindex(d.shape), d.flat):
    if value == d_min:
        f[i] = 0
    elif value == d_max:
        f[i] = 100
    elif value == d_mean:
        f[i] = 50
    elif d_min < value < d_mean:
        f[i] = 25
    elif d_mean < value < d_max:
        f[i] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [42]:
### [your code here]

print(d)
print(f)

[[[1.46328475 1.43723044 1.34640176 1.1842765  1.29498277]
  [1.49840228 1.30465432 1.22538433 1.8161537  1.35192809]
  [1.30895097 1.40848327 1.85813124 1.836447   1.57750169]]

 [[1.70594604 1.30884175 1.58730492 1.32732925 1.48585017]
  [1.47063244 1.9885815  1.39780346 1.23984912 1.18318801]
  [1.82506318 1.35231328 1.66209665 1.34971042 1.42505079]]]
[[[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25. 100.  25.  25.   0.]
  [ 75.  25.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]